name: Deploy
# on – определяет события, которые запускают воркфлоу
on:
  push:
    branches:
      - main
jobs:
  # build – произвольно выбранное имя задания
  # их может быть больше одного
  check:
    # операционная система для работы воркфлоу
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20.2.0
        uses: actions/setup-node@v3
        with:
          node-version: '20.2.0'
          cache: 'npm'
      - name: Install Yarn
        run: npm i -g yarn
      - name: Install Gulp
        run: npm i -g gulp
      - name: Install BEM
        run: npm i -g bem-tools-core